### ISSUE TITLE
xpather does not take into account single quote " ' " when converting

### ISSUE THREAD

**Issue by dguraud** [KnowledgeExpert/xpather#1]
Hello,

I am currently using your xpather into one of my projects and I find it quite useful.

I have some selectors that are made with specific text. If that text happens to have single quote " ' " in it, the selector will fail.
Can You please add a condition so that if the text contains a single quote the delimiter should be double quote instead of single quote.

Thank you!

**Comment by AleksanderPopov** [comment]
hey @dguraud , can you please share the expression and expected/actual results?

**Comment by dguraud** [comment]
Hi @AleksanderPopov,

As an example I am using the With.exactText('the text') or With.text('the text')
This will return a selector similar to this

/.//*[contains (normalize-space(.), 'the text')]
respectively
/.//*[text() = 'the text']

If my text would contain a single quote " ' " (the'text) both selectors will be: 

/.//*[contains (normalize-space(.), 'the'text')]
respectively
/.//*[text() = 'the'text']

These selectors are invalid due to the single quote.

A condition to make the selectors double quotes as delimiters when the text contains a single quote should be added so that selectors will look like this:

/.//*[contains (normalize-space(.), "the'text")]
respectively
/.//*[text() = "the'text"]

Both of the above selectors will work

    export function text(text: string): Condition {
        text.includes("'") ?
        return new Condition(`contains(normalize-space(.), '${text}')`):
	    return new Condition(`contains(normalize-space(.), "${text}")`);
    }

    export function exactText(exactText: string): Condition {
	    exactText.includes("'") ?
        return new Condition(`text() = '${exactText}'`):
	    return new Condition(`contains(normalize-space(.), "${text}")`);
    }

A more complex issue would be when you have both single quote and double quotes present in the text "the"text'"
The only solution I have found for this special case would be to use xpath concat so the selector would be something like this:

/.//*[contains (normalize-space(.), concat('the"text', "'")]
respectively
/.//*[text() = concat('the"text', "'")]

Thank you for the fast reply.

**Comment by dgurauipath** [comment]
Made a mistake on the second function:

export function exactText(exactText: string): Condition {
    exactText.includes("'") ?
    return new Condition(`text() = '${exactText}'`):
    return new Condition(`text() = "${exactText}"`);
}

**Comment by AleksanderPopov** [comment]
hey @dguraud , i'm a bit stucked with some pull requests in selenidejs, can you create a PR for that issue please?

**Comment by dguraud** [comment]
Hi @AleksanderPopov , i've made a PR with the changes, the build from PR seems to have failed though, not sure why.

**Comment by dguraud** [comment]
I see it requires 100% coverage, added the tests for it, should be fine now.

**Comment by AleksanderPopov** [comment]
thanks! merged, will update npm soon

**Comment by AleksanderPopov** [comment]
@dguraud updated with version `0.1.1`, please confirm that it works now

**Comment by dguraud** [comment]
@AleksanderPopov I've updated the compiled js files as well with another pr (with.js and with.js.map). Please have a look.

**Comment by AleksanderPopov** [comment]
@dguraud check `0.1.2`

**Comment by dguraud** [comment]
@AleksanderPopov all good now. It solved my current issue, thank you.
